services:
  appdaemon:
    container_name: appdaemon
    build: ./appdaemon
    env_file: .env
    restart: unless-stopped
    volumes:
      - ./images:/conf/images
      - ./appdaemon/conf/apps/config.ini:/conf/apps/config.ini
